const APP_VERSION="v24-restore-egg-edit";
const CONFIG_KEY="sfm_supabase_config_v1",PENDING_INVITE_KEY="sfm_pending_invite_code",PREFERRED_FARM_KEY="sfm_preferred_farm_id",$=id=>document.getElementById(id);let client=null,session=null,currentFarm=null,farmMemberships=[],farmMode="legacy",data={eggs:[],birds:[],sales:[],uses:[],expenses:[],onHand:[]},pendingImport=[],reportMode="daily",editingEggId=null;
function localIsoDate(dt=new Date()){return dt.getFullYear()+"-"+String(dt.getMonth()+1).padStart(2,"0")+"-"+String(dt.getDate()).padStart(2,"0")}const today=()=>localIsoDate(),money=n=>Number(n||0).toLocaleString(undefined,{style:"currency",currency:"USD"}),num=v=>Number(v||0),setStatus=t=>$("status").textContent=t;
function cfg(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"null")}catch{return null}}function saveCfg(url,key){localStorage.setItem(CONFIG_KEY,JSON.stringify({url:url.trim(),key:key.trim()}))}function show(id){["setupPanel","authPanel","appPanel"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}function dates(){["eggDate","saleDate","useDate","expenseDate","onHandDate"].forEach(id=>{if($(id))$(id).value=today()})}
function authBusy(on,msg){["signInBtn","signUpBtn","resendVerifyBtn","forgotPasswordBtn"].forEach(id=>{if($(id))$(id).disabled=on}); if(msg)$("authMessage").textContent=msg}
function appBaseUrl(){return window.location.origin+window.location.pathname.replace(/[^/]*$/,"")}
function appRedirectUrl(){return appBaseUrl()+"index.html"}
function inviteFromUrl(){try{return new URLSearchParams(window.location.search).get("invite")||new URLSearchParams(window.location.hash.replace(/^#/,"?")).get("invite")||""}catch{return ""}}
function pendingInvite(){return (localStorage.getItem(PENDING_INVITE_KEY)||"").trim().toUpperCase()}
function savePendingInvite(code){code=(code||"").trim().toUpperCase();if(code)localStorage.setItem(PENDING_INVITE_KEY,code)}
function clearPendingInvite(){localStorage.removeItem(PENDING_INVITE_KEY)}
function showInviteNotice(){let code=pendingInvite();if(!$("inviteLinkNotice"))return;$("inviteLinkNotice").classList.toggle("hidden",!code);setText("inviteLinkNoticeText",code?"Invitation code "+code+" is ready. Sign in or create an account, then tap Join Farm.":"")}
function inviteLinkForCode(code){return appBaseUrl()+"?invite="+encodeURIComponent((code||"").trim().toUpperCase())}
function hasAuthCallback(){return /[?&](code|token_hash|error|error_description)=/.test(window.location.search)||/[#&](access_token|refresh_token|error|error_description)=/.test(window.location.hash)}
function cleanAuthUrl(){if(hasAuthCallback())history.replaceState(null,document.title,appRedirectUrl())}
function validateEmail(email){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
async function validateStoredSession(){
  let r=await client.auth.getSession();
  session=r.data.session;
  if(!session) return;
  let u=await client.auth.getUser();
  if(u.error||!u.data?.user){
    await client.auth.signOut();
    session=null;
    setStatus("That saved sign-in is no longer valid. Please sign in or create an account.");
    return;
  }
  session.user=u.data.user;
}
async function init(){dates();savePendingInvite(inviteFromUrl());showInviteNotice();let c=cfg();const fileCfg=window.SFM_CONFIG||{};if(fileCfg.SUPABASE_URL&&fileCfg.SUPABASE_PUBLISHABLE_KEY){c={url:fileCfg.SUPABASE_URL,key:fileCfg.SUPABASE_PUBLISHABLE_KEY};saveCfg(c.url,c.key)}if(!c){show("setupPanel");return}$("supabaseUrl").value=c.url;$("supabaseKey").value=c.key;try{client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"pkce"}});if(hasAuthCallback())setStatus("Finishing email verification...");await validateStoredSession();if(session){cleanAuthUrl();setStatus("Signed in.")}client.auth.onAuthStateChange((event,s)=>{session=s;if(event==="SIGNED_IN")cleanAuthUrl();route()});route();renderDiagnostics()}catch(e){show("setupPanel");setStatus("Connection error.") }}
async function route(){if(!session){show("authPanel");setStatus(pendingInvite()?"Invitation saved. Sign in or create an account to join the farm.":"Connected. Sign in required.");showInviteNotice();return}$("signedInAs").textContent="Signed in as "+(session.user?.email||"your account");show("appPanel");if(pendingInvite()){await ensureFarmReady({createIfMissing:false});await maybeAutoJoinPendingInvite();if(!currentFarm)await ensureFarmReady()}else await ensureFarmReady();await loadAll();showInviteNotice()}
$("saveConfigBtn").onclick=()=>{saveCfg($("supabaseUrl").value,$("supabaseKey").value);location.reload()};
function authFields(){return {email:$("emailInput").value.trim().toLowerCase(),password:$("passwordInput").value}}
function authValidation(email,password,needPassword=true){if(!email)return "Enter your email address.";if(!validateEmail(email))return "Enter a valid email address.";if(needPassword&&!password)return "Enter your password.";if(needPassword&&password.length<6)return "Password must be at least 6 characters.";return ""}
$("signInBtn").onclick=async()=>{let {email,password}=authFields(),v=authValidation(email,password);if(v){$("authMessage").textContent=v;return}authBusy(true,"Signing in. Please wait...");let {error}=await client.auth.signInWithPassword({email,password});authBusy(false);if(error){$("authMessage").textContent=friendlyAuthError(error.message)}else $("authMessage").textContent="Signed in.";};
$("signUpBtn").onclick=async()=>{let {email,password}=authFields(),v=authValidation(email,password);if(v){$("authMessage").textContent=v;return}authBusy(true,"Creating account. Please wait...");let {data:signUpData,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:appRedirectUrl()}});authBusy(false);if(error){$("authMessage").textContent=friendlyAuthError(error.message);return}if(signUpData?.session){$("authMessage").textContent="Account created and signed in."}else{$("authMessage").textContent="Account created. Check your email and tap the verification link. It should return you to this app."}};
$("resendVerifyBtn").onclick=async()=>{let {email}=authFields(),v=authValidation(email,"",false);if(v){$("authMessage").textContent=v;return}authBusy(true,"Sending a fresh verification email...");let {error}=await client.auth.resend({type:"signup",email,options:{emailRedirectTo:appRedirectUrl()}});authBusy(false);$("authMessage").textContent=error?friendlyAuthError(error.message):"Verification email resent. Use the newest email link."};
$("forgotPasswordBtn").onclick=async()=>{let {email}=authFields(),v=authValidation(email,"",false);if(v){$("authMessage").textContent=v;return}authBusy(true,"Sending password reset email...");let {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:appRedirectUrl()});authBusy(false);$("authMessage").textContent=error?friendlyAuthError(error.message):"Password reset email sent. Use the newest email link."};
function friendlyAuthError(m){if(!m)return "Something went wrong. Please try again.";if(/rate limit/i.test(m))return "Too many attempts. Wait a few minutes, then try once.";if(/email not confirmed/i.test(m))return "Email is not verified yet. Check your email, or use Resend Verification Email.";if(/invalid login|invalid credentials/i.test(m))return "Invalid email or password. If this is your first time, use Create Account once.";if(/already registered|already exists|user already/i.test(m))return "That account already exists. Use Sign In, or use Forgot Password if needed.";if(/redirect|not allowed/i.test(m))return "The verification redirect is not allowed in Supabase. Add this app URL to Supabase Auth Redirect URLs: "+appRedirectUrl();return m}
$("signOutBtn").onclick=async()=>{await client.auth.signOut();session=null;route()};$("resetConfigBtn").onclick=()=>{if(confirm("Reset connection settings?")){localStorage.removeItem(CONFIG_KEY);location.reload()}};$("syncBtn").onclick=()=>loadAll();
function renderDiagnostics(){if(!$("diagAppVersion"))return;let c=cfg()||{};setText("diagAppVersion",APP_VERSION);setText("diagAppUrl",appBaseUrl());setText("diagRedirectUrl",appRedirectUrl());setText("diagSupabaseUrl",c.url||"not set");setText("diagAuthStatus",session?"Signed in as "+(session.user?.email||"user")+" | Farm mode: "+farmMode+(currentFarm?" | Farm: "+currentFarm.name:""):"Not signed in");setText("farmStatus",farmMode==="shared"&&currentFarm?"Current farm: "+currentFarm.name:"Shared farm setup not installed yet. Run the v21 SQL migration.");setText("diagUserId",session?.user?.id||"not signed in");showInviteNotice()}

async function ensureFarmReady(options={}){farmMode="legacy";currentFarm=null;farmMemberships=[];let createIfMissing=options.createIfMissing!==false,preferredFarmId=options.preferredFarmId||localStorage.getItem(PREFERRED_FARM_KEY)||"";try{let {data:members,error}=await client.from("farm_members").select("id,farm_id,role,farms(id,name,owner_id)").eq("user_id",session.user.id).order("created_at",{ascending:true});if(error){console.warn("Farm sharing tables not ready",error.message);farmMode="legacy";return}farmMode="shared";farmMemberships=members||[];if(!farmMemberships.length){if(!createIfMissing){renderFarmPanel();return}let farmName=(session.user.email||"My").split("@")[0]+" Farm";let {data:farm,error:farmErr}=await client.from("farms").insert({name:farmName,owner_id:session.user.id}).select("id,name,owner_id").single();if(farmErr){setStatus("Farm setup failed: "+farmErr.message);return}let {error:memErr}=await client.from("farm_members").insert({farm_id:farm.id,user_id:session.user.id,role:"owner"});if(memErr){setStatus("Farm membership failed: "+memErr.message);return}localStorage.setItem(PREFERRED_FARM_KEY,farm.id);currentFarm=farm;farmMemberships=[{farm_id:farm.id,role:"owner",farms:farm}]}else{let match=farmMemberships.find(m=>m.farm_id===preferredFarmId);currentFarm=(match||farmMemberships[0]).farms||null;if(currentFarm)localStorage.setItem(PREFERRED_FARM_KEY,currentFarm.id)}renderFarmPanel()}catch(e){console.warn(e);farmMode="legacy"}}
function farmScoped(q){return farmMode==="shared"&&currentFarm?q.eq("farm_id",currentFarm.id):q}
function withFarm(row){return farmMode==="shared"&&currentFarm?{...row,farm_id:currentFarm.id}:row}
function canManageFarm(){let m=farmMemberships.find(x=>x.farm_id===currentFarm?.id);return ["owner","admin"].includes(m?.role)}
function renderFarmPanel(){if(!$("farmStatus"))return;showInviteNotice();if($("joinCode")&&pendingInvite()&&!$("joinCode").value)$("joinCode").value=pendingInvite();setText("farmStatus",farmMode==="shared"&&currentFarm?"Current farm: "+currentFarm.name:"Shared farm setup not installed yet. Run the v21 SQL migration.");let sel=$("farmSelect");if(sel){sel.innerHTML=farmMemberships.map(m=>`<option value="${m.farm_id}">${m.farms?.name||"Farm"} (${m.role})</option>`).join("");if(currentFarm)sel.value=currentFarm.id}let manage=canManageFarm();["createInviteBtn","inviteRole"].forEach(id=>{if($(id))$(id).disabled=!manage});setText("farmHelp",manage?"Create an invite code for a family member, or enter a code to join someone else's farm.":"You can join another farm with an invite code. Only owners/admins can create invite codes.")}
async function refreshMemberships(){await ensureFarmReady();await loadAll()}

document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
["Daily","Weekly","Monthly"].forEach(m=>{let b=$("report"+m+"Btn");if(b)b.onclick=()=>{reportMode=m.toLowerCase();document.querySelectorAll(".reportControls button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderReports()}});
async function loadAll(){setStatus("Syncing..."+((farmMode==="shared"&&currentFarm)?" "+currentFarm.name:""));const [eggs,birds,sales,uses,expenses,onHand]=await Promise.all([farmScoped(client.from("egg_entries").select("*")).order("entry_date",{ascending:false}),farmScoped(client.from("flock").select("*")).order("created_at",{ascending:false}),farmScoped(client.from("sales").select("*")).order("sale_date",{ascending:false}),farmScoped(client.from("household_use").select("*")).order("use_date",{ascending:false}),farmScoped(client.from("expenses").select("*")).order("expense_date",{ascending:false}),farmScoped(client.from("egg_on_hand_counts").select("*")).order("entry_date",{ascending:false})]);let err=[eggs,birds,sales,uses,expenses].find(r=>r.error);if(err){setStatus("Sync failed: "+err.error.message);return}let onHandData=[];if(onHand.error){console.warn("Eggs on hand table unavailable",onHand.error.message);setStatus("Synced. Eggs on hand needs the database update.")}else onHandData=onHand.data;data={eggs:eggs.data||[],birds:birds.data||[],sales:sales.data||[],uses:uses.data||[],expenses:expenses.data||[],onHand:onHandData};render();setStatus("Synced "+new Date().toLocaleTimeString());renderDiagnostics();renderFarmPanel()}
async function insert(table,row){setStatus("Saving...");let {error}=await client.from(table).insert(withFarm(row));if(error){alert(error.message);setStatus("Save failed")}else await loadAll()}async function updateRow(table,id,row){setStatus("Saving changes...");let q=client.from(table).update(row).eq("id",id);q=farmScoped(q);let {error}=await q;if(error){alert(error.message);setStatus("Update failed")}else await loadAll()}async function upsert(table,row,onConflict){setStatus("Saving...");let finalRow=withFarm(row),conflict=(farmMode==="shared"&&table==="egg_on_hand_counts")?"farm_id,entry_date":onConflict;let {error}=await client.from(table).upsert(finalRow,{onConflict:conflict});if(error){let msg=error.message;if(table==="egg_on_hand_counts"&&msg.includes("Could not find the table")){msg="Eggs on Hand needs the database update before it can save. Run the SQL file included in this ZIP once in Supabase, then refresh the app."}alert(msg);setStatus("Save failed")}else await loadAll()}async function del(table,id){if(!confirm("Delete this record?"))return;let q=client.from(table).delete().eq("id",id);q=farmScoped(q);let {error}=await q;if(error)alert(error.message);else await loadAll()}
$("eggForm").onsubmit=async e=>{e.preventDefault();let row={entry_date:$("eggDate").value,eggs_collected:num($("eggCollected").value),broken_discarded:num($("eggBroken").value),notes:$("eggNotes").value};if(editingEggId){await updateRow("egg_entries",editingEggId,row);editingEggId=null;setEggEditMode(false)}else await insert("egg_entries",row);e.target.reset();dates()};if($("cancelEggEditBtn"))$("cancelEggEditBtn").onclick=()=>{editingEggId=null;$("eggForm").reset();dates();setEggEditMode(false);setStatus("Egg edit cancelled.")};$("birdForm").onsubmit=e=>{e.preventDefault();insert("flock",{name:$("birdName").value,breed:$("birdBreed").value,status:$("birdStatus").value,acquired_date:$("birdDate").value||null,notes:$("birdNotes").value});e.target.reset()};$("saleForm").onsubmit=e=>{e.preventDefault();insert("sales",{sale_date:$("saleDate").value,customer:$("saleCustomer").value,dozens:num($("saleDozens").value),price_per_dozen:num($("salePrice").value),paid:$("salePaid").value==="true",notes:$("saleNotes").value});e.target.reset();$("salePrice").value="5.00";dates()};$("useForm").onsubmit=e=>{e.preventDefault();insert("household_use",{use_date:$("useDate").value,eggs_used:num($("useEggs").value),purpose:$("usePurpose").value});e.target.reset();dates()};$("expenseForm").onsubmit=e=>{e.preventDefault();insert("expenses",{expense_date:$("expenseDate").value,category:$("expenseCategory").value,amount:num($("expenseAmount").value),notes:$("expenseNotes").value});e.target.reset();dates()};$("onHandForm").onsubmit=e=>{e.preventDefault();upsert("egg_on_hand_counts",{user_id:session.user.id,entry_date:$("onHandDate").value,eggs_on_hand:num($("onHandCount").value),notes:$("onHandNotes").value},"user_id,entry_date");e.target.reset();dates()};
function table(id,rows,headers,map,tableName){$(id).innerHTML="<tr>"+headers.map(h=>`<th>${h}</th>`).join("")+"<th></th></tr>"+rows.map(r=>"<tr>"+map(r).map(v=>`<td>${v??""}</td>`).join("")+`<td>${tableName==="egg_entries"?`<button onclick="editEgg('${r.id}')">Edit</button> `:""}<button onclick="del('${tableName}','${r.id}')">Delete</button></td></tr>`).join("")}
function setEggEditMode(on){let b=$("eggSaveBtn"),c=$("cancelEggEditBtn"),n=$("eggEditNotice");if(b)b.textContent=on?"Save Changes":"Save Egg Entry";if(c)c.classList.toggle("hidden",!on);if(n)n.classList.toggle("hidden",!on)}
function editEgg(id){let r=data.eggs.find(x=>String(x.id)===String(id));if(!r)return;editingEggId=r.id;$("eggDate").value=r.entry_date;$("eggCollected").value=r.eggs_collected;$("eggBroken").value=r.broken_discarded||0;$("eggNotes").value=r.notes||"";setEggEditMode(true);document.querySelector('button[data-tab="eggs"]').click();$("eggCollected").focus();setStatus("Editing egg entry for "+prettyDayLong(r.entry_date)+".")}

function editOnHand(id){let r=data.onHand.find(x=>String(x.id)===String(id));if(!r)return;$("onHandDate").value=r.entry_date;$("onHandCount").value=r.eggs_on_hand;$("onHandNotes").value=r.notes||"";document.querySelector('button[data-tab="onhand"]').click();$("onHandCount").focus();setStatus("Editing eggs on hand for "+prettyDayLong(r.entry_date)+". Save Count will update that date.")}
function onHandTable(){let rows=data.onHand||[];$("onHandTable").innerHTML="<tr><th>Date</th><th>Eggs on hand</th><th>Notes</th><th></th></tr>"+rows.map(r=>`<tr><td>${r.entry_date}</td><td>${r.eggs_on_hand}</td><td>${r.notes||""}</td><td><button onclick="editOnHand('${r.id}')">Edit</button> <button onclick="del('egg_on_hand_counts','${r.id}')">Delete</button></td></tr>`).join("")}
function relativeDayText(iso){
  if(!iso) return "unknown";
  let a=new Date(iso+"T00:00:00"), b=dateOnly(new Date());
  let days=Math.round((b-a)/86400000);
  if(days===0) return "today";
  if(days===1) return "yesterday";
  if(days>1) return days+" days ago";
  if(days===-1) return "tomorrow";
  return prettyDayLong(iso);
}
function render(){let d=today(),ym=d.slice(0,7),now=dateOnly(new Date()),w=addDays(now,-6),ws=isoDate(w),mStartIso=ym+"-01",active=data.birds.filter(x=>["Laying","Molting","Broody"].includes(x.status)).length,week=data.eggs.filter(x=>x.entry_date>=ws&&x.entry_date<=d).reduce((a,x)=>a+num(x.eggs_collected),0),todayEggs=data.eggs.filter(x=>x.entry_date===d).reduce((a,x)=>a+num(x.eggs_collected),0),monthRange=dateRangeText(mStartIso,d),weekRange=dateRangeText(ws,d);setText("todayCardLabel","Today ("+prettyDayLong(d)+")");setText("weekCardLabel","Last 7 days ("+weekRange+")");setText("monthEggsLabel","eggs this month ("+monthRange+")");setText("eggsPerHenLabel","eggs / hen last 7 days ("+weekRange+")");setText("monthExpensesLabel","expenses this month ("+monthRange+")");$("todayEggs").textContent=todayEggs;$("weekEggs").textContent=week;let latestOnHand=data.onHand[0];setText("eggsOnHandLabel",latestOnHand?"Eggs on hand ("+prettyDayLong(latestOnHand.entry_date)+")":"Eggs on hand");$("eggsOnHand").textContent=latestOnHand?num(latestOnHand.eggs_on_hand):0;setText("eggsOnHandSub",latestOnHand?"last counted "+relativeDayText(latestOnHand.entry_date):"not counted yet");let rate=active?Math.round((todayEggs/active)*100):0;setText("layingRateLabel","Laying rate ("+prettyDayLong(d)+")");$("layingRate").textContent=rate+"%";setText("layingRateSub",active?todayEggs+" of "+active+" active layers":"add flock records");$("monthEggs").textContent=data.eggs.filter(x=>x.entry_date?.startsWith(ym)).reduce((a,x)=>a+num(x.eggs_collected),0);$("activeLayers").textContent=active;$("eggsPerHen").textContent=active?(week/active).toFixed(1):"0";$("monthExpenses").textContent=money(data.expenses.filter(x=>x.expense_date?.startsWith(ym)).reduce((a,x)=>a+num(x.amount),0));table("recentEggTable",data.eggs.slice(0,10),["Date","Collected","Broken","Notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes],"egg_entries");table("eggTable",data.eggs,["Date","Collected","Broken","Notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes],"egg_entries");table("birdTable",data.birds,["Name","Breed","Status","Date","Notes"],r=>[r.name,r.breed,r.status,r.acquired_date,r.notes],"flock");table("saleTable",data.sales,["Date","Customer","Dozens","Price","Total","Paid","Notes"],r=>[r.sale_date,r.customer,r.dozens,money(r.price_per_dozen),money(num(r.dozens)*num(r.price_per_dozen)),r.paid?"Yes":"No",r.notes],"sales");table("useTable",data.uses,["Date","Eggs","Purpose"],r=>[r.use_date,r.eggs_used,r.purpose],"household_use");table("expenseTable",data.expenses,["Date","Category","Amount","Notes"],r=>[r.expense_date,r.category,money(r.amount),r.notes],"expenses");onHandTable();renderDashboardChart();renderReports()}

function dateOnly(dt){return new Date(dt.getFullYear(),dt.getMonth(),dt.getDate())}
function isoDate(dt){return localIsoDate(dateOnly(dt))}
function addDays(dt,n){let d=dateOnly(dt);d.setDate(d.getDate()+n);return d}
function addMonths(dt,n){let d=new Date(dt.getFullYear(),dt.getMonth()+n,1);return d}
function startOfWeek(dt){let d=dateOnly(dt),day=d.getDay();d.setDate(d.getDate()-day);return d}
function monthKey(dt){return dt.getFullYear()+"-"+String(dt.getMonth()+1).padStart(2,"0")}
function prettyDay(iso){let [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{month:"short",day:"numeric"})}
function prettyDayLong(iso){let [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}
function dateRangeText(startIso,endIso){return startIso===endIso?prettyDayLong(startIso):prettyDay(startIso)+"–"+prettyDayLong(endIso)}
function setText(id,text){let el=$(id);if(el)el.textContent=text}
function prettyMonth(key){let [y,m]=key.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:"short",year:"2-digit"})}
function eggTotal(start,end){return data.eggs.filter(x=>x.entry_date>=start&&x.entry_date<=end).reduce((a,x)=>a+num(x.eggs_collected),0)}
function eggsByDate(){let m={};data.eggs.forEach(x=>{if(x.entry_date)m[x.entry_date]=(m[x.entry_date]||0)+num(x.eggs_collected)});return m}
function renderBarChart(rows,title,sub){let el=$("eggChart");if(!el)return;$("reportChartTitle").textContent=title;$("reportChartSub").textContent=sub;let total=rows.reduce((a,r)=>a+r.value,0);$("reportChartTotal").textContent=total+" eggs";if(!rows.length){el.innerHTML='<div class="emptyChart">No egg data yet.</div>';return}let max=Math.max(...rows.map(r=>r.value),1);el.innerHTML=rows.map((r,i)=>`<button class="barRow chartButton" type="button" data-detail="${r.detail||r.label+': '+r.value+' eggs'}"><span class="barLabel">${r.label}</span><span class="barTrack"><span class="barFill" style="width:${Math.max(3,(r.value/max)*100)}%"></span></span><span class="barValue">${r.value}</span></button>`).join("");el.querySelectorAll(".chartButton").forEach(b=>b.onclick=()=>setStatus(b.dataset.detail))}
function reportRows(){let map=eggsByDate(),now=dateOnly(new Date());if(reportMode==="weekly"){let start=startOfWeek(addDays(now,-77)),rows=[],firstIso="",lastIso="";for(let i=0;i<12;i++){let s=addDays(start,i*7),e=addDays(s,6),startIso=isoDate(s),endIso=isoDate(e),v=eggTotal(startIso,endIso);if(i===0)firstIso=startIso;if(i===11)lastIso=endIso;rows.unshift({label:prettyDay(startIso),value:v,detail:`${dateRangeText(startIso,endIso)}: ${v} eggs`})}return {rows,title:"Weekly Egg Production",sub:"Last 12 calendar weeks ("+dateRangeText(firstIso,lastIso)+")"}}if(reportMode==="monthly"){let start=addMonths(now,-11),rows=[],firstIso=isoDate(start),lastIso=isoDate(new Date(now.getFullYear(),now.getMonth()+1,0));for(let i=0;i<12;i++){let d=addMonths(start,i),key=monthKey(d),v=data.eggs.filter(x=>x.entry_date?.startsWith(key)).reduce((a,x)=>a+num(x.eggs_collected),0);rows.unshift({label:prettyMonth(key),value:v,detail:`${prettyMonth(key)} (${dateRangeText(key+"-01",isoDate(new Date(d.getFullYear(),d.getMonth()+1,0))) }): ${v} eggs`})}return {rows,title:"Monthly Egg Production",sub:"Last 12 months ("+dateRangeText(firstIso,lastIso)+")"}}let start=addDays(now,-29),startIso=isoDate(start),endIso=isoDate(now),rows=[];for(let i=0;i<30;i++){let d=isoDate(addDays(start,i));rows.unshift({label:prettyDay(d),value:map[d]||0,detail:`${prettyDayLong(d)}: ${map[d]||0} eggs`})}return {rows,title:"Daily Egg Production",sub:"Last 30 days ("+dateRangeText(startIso,endIso)+")"}}

function renderDashboardChart(){let el=$("dashboardChart");if(!el)return;let map=eggsByDate(),now=dateOnly(new Date()),start=addDays(now,-13),startIso=isoDate(start),endIso=isoDate(now),rows=[];for(let i=0;i<14;i++){let d=isoDate(addDays(start,i));rows.unshift({date:d,label:prettyDay(d),value:map[d]||0})}let range14=dateRangeText(startIso,endIso);setText("dash14Title","Last 14 days ("+range14+")");let total=rows.reduce((a,r)=>a+r.value,0);$("dash14Total").textContent=total+" eggs";let max=Math.max(...rows.map(r=>r.value),1);el.innerHTML=rows.map(r=>`<button class="barRow chartButton" type="button" data-date="${r.date}" data-value="${r.value}"><span class="barLabel">${r.label}</span><span class="barTrack"><span class="barFill" style="width:${Math.max(3,(r.value/max)*100)}%"></span></span><span class="barValue">${r.value}</span></button>`).join("");el.querySelectorAll(".chartButton").forEach(b=>b.onclick=()=>{$("dashboardChartDetail").textContent=`${prettyDayLong(b.dataset.date)}: ${b.dataset.value} eggs collected.`});let last7Start=isoDate(addDays(now,-6)),last7=rows.slice(0,7).reduce((a,r)=>a+r.value,0);setText("dash7AvgLabel","7-day average ("+dateRangeText(last7Start,endIso)+")");$("dash7Avg").textContent=(last7/7).toFixed(1);let ym=today().slice(0,7),monthStartIso=ym+"-01",monthEggs=data.eggs.filter(x=>x.entry_date?.startsWith(ym)).reduce((a,x)=>a+num(x.eggs_collected),0),dayOfMonth=new Date().getDate(),daysInMonth=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate();setText("dashMonthPaceLabel","Month pace ("+dateRangeText(monthStartIso,endIso)+")");$("dashMonthPace").textContent=Math.round(monthEggs/dayOfMonth*daysInMonth);let best=data.eggs.reduce((best,x)=>num(x.eggs_collected)>best.eggs?{eggs:num(x.eggs_collected),date:x.entry_date}:best,{eggs:0,date:""});$("dashBestDay").textContent=best.eggs?best.eggs+" on "+prettyDayLong(best.date):"0";$("dashLastEntry").textContent=data.eggs[0]?.entry_date?prettyDayLong(data.eggs[0].entry_date):"None"}
function renderReports(){if(!$('reportSummaryTable'))return;let now=dateOnly(new Date()),nowIso=isoDate(now),yStart=new Date(now.getFullYear(),0,1),last7Start=addDays(now,-6),mStart=new Date(now.getFullYear(),now.getMonth(),1);let all=data.eggs.filter(x=>x.entry_date).sort((a,b)=>a.entry_date.localeCompare(b.entry_date));let firstIso=all[0]?.entry_date||nowIso,lifetime=data.eggs.reduce((a,x)=>a+num(x.eggs_collected),0),todayTotal=eggTotal(nowIso,nowIso),last7Total=eggTotal(isoDate(last7Start),nowIso),mtdTotal=eggTotal(isoDate(mStart),nowIso),ytdTotal=eggTotal(isoDate(yStart),nowIso);let summaryRows=[['Today',prettyDayLong(nowIso),todayTotal],['Last 7 days',dateRangeText(isoDate(last7Start),nowIso),last7Total],['Month to date',dateRangeText(isoDate(mStart),nowIso),mtdTotal],['Year to date',dateRangeText(isoDate(yStart),nowIso),ytdTotal],['Lifetime',dateRangeText(firstIso,nowIso),lifetime]];$('reportSummaryTable').innerHTML='<tr><th>Period</th><th>Date Range</th><th>Eggs</th></tr>'+summaryRows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="numCell">${r[2]}</td></tr>`).join('');let uniqueDays=new Set(data.eggs.filter(x=>x.entry_date).map(x=>x.entry_date)).size;$('reportAvgDay').textContent=uniqueDays?(lifetime/uniqueDays).toFixed(1):"0";$('reportLifetime').textContent=lifetime;let weekTotals={},monthTotals={};data.eggs.forEach(x=>{if(!x.entry_date)return;let d=new Date(x.entry_date+"T00:00:00"),wk=isoDate(startOfWeek(d)),mk=x.entry_date.slice(0,7);weekTotals[wk]=(weekTotals[wk]||0)+num(x.eggs_collected);monthTotals[mk]=(monthTotals[mk]||0)+num(x.eggs_collected)});$('reportBestWeek').textContent=Math.max(0,...Object.values(weekTotals));$('reportBestMonth').textContent=Math.max(0,...Object.values(monthTotals));let r=reportRows();renderBarChart(r.rows,r.title,r.sub)}

function esc(v){return `"${String(v??"").replaceAll('"','""')}"`}function csv(rows,headers,map){return headers.join(",")+"\n"+rows.map(r=>map(r).map(esc).join(",")).join("\n")}function dl(name,content,type="text/csv"){let a=document.createElement("a"),blob=new Blob([content],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("exportEggs").onclick=()=>dl("shearin-farm-eggs.csv",csv(data.eggs,["date","eggs_collected","broken_discarded","notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes]));$("exportFlock").onclick=()=>dl("shearin-farm-flock.csv",csv(data.birds,["name","breed","status","date","notes"],r=>[r.name,r.breed,r.status,r.acquired_date,r.notes]));$("exportSales").onclick=()=>dl("shearin-farm-sales.csv",csv(data.sales,["date","customer","dozens","price_per_dozen","paid","notes"],r=>[r.sale_date,r.customer,r.dozens,r.price_per_dozen,r.paid,r.notes]));$("exportUse").onclick=()=>dl("shearin-farm-use.csv",csv(data.uses,["date","eggs_used","purpose"],r=>[r.use_date,r.eggs_used,r.purpose]));$("exportOnHand").onclick=()=>dl("shearin-farm-eggs-on-hand.csv",csv(data.onHand,["date","eggs_on_hand","notes"],r=>[r.entry_date,r.eggs_on_hand,r.notes]));$("exportExpenses").onclick=()=>dl("shearin-farm-expenses.csv",csv(data.expenses,["date","category","amount","notes"],r=>[r.expense_date,r.category,r.amount,r.notes]));$("exportBackup").onclick=()=>dl("shearin-farm-backup.json",JSON.stringify(data,null,2),"application/json");
function parseCSV(text){let lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];let headers=lines[0].split(",").map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{let parts=line.split(",");let obj={};headers.forEach((h,i)=>obj[h]=(parts[i]||"").trim());return obj})}
$("previewEggImport").onclick=()=>{pendingImport=parseCSV($("eggImportText").value).map(r=>({entry_date:r.date,eggs_collected:num(r.eggs_collected),broken_discarded:num(r.broken_discarded),notes:r.notes||""})).filter(r=>r.entry_date);$("importMessage").textContent=`Previewing ${pendingImport.length} rows.`;$("runEggImport").classList.toggle("hidden",pendingImport.length===0);$("importPreviewTable").innerHTML="<tr><th>Date</th><th>Eggs</th><th>Broken</th><th>Notes</th></tr>"+pendingImport.map(r=>`<tr><td>${r.entry_date}</td><td>${r.eggs_collected}</td><td>${r.broken_discarded}</td><td>${r.notes}</td></tr>`).join("")};
$("runEggImport").onclick=async()=>{if(!pendingImport.length)return;if(!confirm(`Import ${pendingImport.length} egg rows?`))return;let {error}=await client.from("egg_entries").insert(pendingImport.map(withFarm));if(error){$("importMessage").textContent=error.message}else{$("importMessage").textContent="Import complete.";pendingImport=[];$("runEggImport").classList.add("hidden");await loadAll()}};

if($("farmSelect"))$("farmSelect").onchange=async()=>{let m=farmMemberships.find(x=>x.farm_id===$("farmSelect").value);if(m){currentFarm=m.farms;localStorage.setItem(PREFERRED_FARM_KEY,currentFarm.id);renderFarmPanel();await loadAll()}};
function inviteShareText(link){return "You've been invited to join "+(currentFarm?.name||"our farm")+" in Shearin Farm Manager. Tap this link to join: "+link}
async function copyInviteLink(){let link=$("inviteLinkDisplay")?.value||"";if(!link)return;try{await navigator.clipboard.writeText(link);$("farmMessage").textContent="Invite link copied. You can paste it into a text message or email."}catch{$("inviteLinkDisplay").select();$("farmMessage").textContent="Copy failed automatically. The link is selected so you can copy it manually."}}
async function shareInviteLink(){let link=$("inviteLinkDisplay")?.value||"";if(!link)return;let text=inviteShareText(link);if(navigator.share){try{await navigator.share({title:"Join "+(currentFarm?.name||"my farm"),text,url:link});$("farmMessage").textContent="Invitation shared.";return}catch(e){if(e?.name==="AbortError")return}}await copyInviteLink()}
async function joinFarmByCode(code,quiet=false){code=(code||"").trim().toUpperCase();if(!code){if(!quiet)$("farmMessage").textContent="Enter an invite code.";return false}let {data:invite,error}=await client.from("farm_invites").select("farm_id,role,expires_at").eq("code",code).maybeSingle();if(error||!invite){if(!quiet)$("farmMessage").textContent=error?error.message:"Invite code not found.";return false}if(invite.expires_at&&new Date(invite.expires_at)<new Date()){if(!quiet)$("farmMessage").textContent="That invite code has expired.";return false}let already=farmMemberships.some(m=>m.farm_id===invite.farm_id);if(already){clearPendingInvite();localStorage.setItem(PREFERRED_FARM_KEY,invite.farm_id);if(!quiet)$("farmMessage").textContent="You already belong to this farm.";await ensureFarmReady({preferredFarmId:invite.farm_id});await loadAll();return true}let {error:joinErr}=await client.from("farm_members").insert({farm_id:invite.farm_id,user_id:session.user.id,role:invite.role||"viewer"});if(joinErr&&/duplicate/i.test(joinErr.message)){joinErr=null}if(joinErr){if(!quiet)$("farmMessage").textContent=joinErr.message;return false}clearPendingInvite();localStorage.setItem(PREFERRED_FARM_KEY,invite.farm_id);if(!quiet)$("farmMessage").textContent="Farm joined. Syncing shared data...";await ensureFarmReady({preferredFarmId:invite.farm_id});await loadAll();return true}
async function maybeAutoJoinPendingInvite(){let code=pendingInvite();if(!code||farmMode!=="shared")return false;if($("joinCode"))$("joinCode").value=code;setStatus("Joining invited farm...");return await joinFarmByCode(code,true)}
if($("createInviteBtn"))$("createInviteBtn").onclick=async()=>{if(farmMode!=="shared"||!currentFarm){$("farmMessage").textContent="Run the v21 SQL migration first.";return}if(!canManageFarm()){$("farmMessage").textContent="Only farm owners/admins can create invite codes.";return}let code=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random()).replaceAll("-","").slice(0,8).toUpperCase(),role=$("inviteRole").value||"editor";let {error}=await client.from("farm_invites").insert({farm_id:currentFarm.id,code,role,created_by:session.user.id});if(error){$("farmMessage").textContent=error.message;return}let link=inviteLinkForCode(code);if($("inviteResult"))$("inviteResult").classList.remove("hidden");setText("inviteCodeDisplay",code);if($("inviteLinkDisplay"))$("inviteLinkDisplay").value=link;$("farmMessage").textContent="Invite ready. Use Share Invitation or Copy Invite Link."};
if($("copyInviteLinkBtn"))$("copyInviteLinkBtn").onclick=copyInviteLink;
if($("shareInviteLinkBtn"))$("shareInviteLinkBtn").onclick=shareInviteLink;
if($("joinFarmBtn"))$("joinFarmBtn").onclick=async()=>{await joinFarmByCode($("joinCode").value,false)};

function registerAutoUpdateServiceWorker(){
  if (!("serviceWorker" in navigator)) return;
  let refreshing = false;
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (refreshing) return;
    refreshing = true;
    window.location.reload();
  });
  window.addEventListener("load", async () => {
    try {
      const reg = await navigator.serviceWorker.register("sw.js?v=22", { updateViaCache: "none" });
      await reg.update();
      if (reg.waiting) reg.waiting.postMessage({ type: "SKIP_WAITING" });
      reg.addEventListener("updatefound", () => {
        const worker = reg.installing;
        if (!worker) return;
        worker.addEventListener("statechange", () => {
          if (worker.state === "installed" && navigator.serviceWorker.controller) {
            worker.postMessage({ type: "SKIP_WAITING" });
          }
        });
      });
    } catch (e) {
      console.warn("Service worker update check failed", e);
    }
  });
}
registerAutoUpdateServiceWorker();
init();