const CONFIG_KEY="sfm_supabase_config_v1",$=id=>document.getElementById(id);let client=null,session=null,data={eggs:[],birds:[],sales:[],uses:[],expenses:[]},pendingImport=[],reportMode="daily";
const today=()=>new Date().toISOString().slice(0,10),money=n=>Number(n||0).toLocaleString(undefined,{style:"currency",currency:"USD"}),num=v=>Number(v||0),setStatus=t=>$("status").textContent=t;
function cfg(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"null")}catch{return null}}function saveCfg(url,key){localStorage.setItem(CONFIG_KEY,JSON.stringify({url:url.trim(),key:key.trim()}))}function show(id){["setupPanel","authPanel","appPanel"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}function dates(){["eggDate","saleDate","useDate","expenseDate"].forEach(id=>{if($(id))$(id).value=today()})}
function authBusy(on,msg){["signInBtn","signUpBtn"].forEach(id=>$(id).disabled=on); if(msg)$("authMessage").textContent=msg}
async function init(){dates();let c=cfg();const fileCfg=window.SFM_CONFIG||{};if(fileCfg.SUPABASE_URL&&fileCfg.SUPABASE_PUBLISHABLE_KEY){c={url:fileCfg.SUPABASE_URL,key:fileCfg.SUPABASE_PUBLISHABLE_KEY};saveCfg(c.url,c.key)}if(!c){show("setupPanel");return}$("supabaseUrl").value=c.url;$("supabaseKey").value=c.key;try{client=window.supabase.createClient(c.url,c.key);let r=await client.auth.getSession();session=r.data.session;client.auth.onAuthStateChange((_e,s)=>{session=s;route()});route()}catch(e){show("setupPanel");setStatus("Connection error.")}}
async function route(){if(!session){show("authPanel");setStatus("Connected. Sign in required.");return}$("signedInAs").textContent="Signed in as "+(session.user?.email||"your account");show("appPanel");await loadAll()}
$("saveConfigBtn").onclick=()=>{saveCfg($("supabaseUrl").value,$("supabaseKey").value);location.reload()};
function authFields(){return {email:$("emailInput").value.trim().toLowerCase(),password:$("passwordInput").value}}
$("signInBtn").onclick=async()=>{let {email,password}=authFields();if(!email||!password){$("authMessage").textContent="Enter email and password.";return}authBusy(true,"Signing in. Please wait...");let {error}=await client.auth.signInWithPassword({email,password});if(error){authBusy(false, friendlyAuthError(error.message));}else $("authMessage").textContent="Signed in.";};
$("signUpBtn").onclick=async()=>{let {email,password}=authFields();if(!email||!password){$("authMessage").textContent="Enter email and password.";return}if(password.length<6){$("authMessage").textContent="Password must be at least 6 characters.";return}authBusy(true,"Creating account. Please wait...");let {error}=await client.auth.signUp({email,password});if(error){authBusy(false, friendlyAuthError(error.message));}else $("authMessage").textContent="Account created. You should now be signed in.";};
function friendlyAuthError(m){if(/rate limit/i.test(m))return "Too many attempts. Stop clicking and wait for Supabase to cool down, then try once.";if(/invalid login/i.test(m))return "Invalid email or password. If this is your first time, use Create Account once.";if(/already registered|already exists/i.test(m))return "That account already exists. Use Sign In instead.";return m}
$("signOutBtn").onclick=async()=>{await client.auth.signOut();session=null;route()};$("resetConfigBtn").onclick=()=>{if(confirm("Reset connection settings?")){localStorage.removeItem(CONFIG_KEY);location.reload()}};$("syncBtn").onclick=()=>loadAll();
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
["Daily","Weekly","Monthly"].forEach(m=>{let b=$("report"+m+"Btn");if(b)b.onclick=()=>{reportMode=m.toLowerCase();document.querySelectorAll(".reportControls button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderReports()}});
async function loadAll(){setStatus("Syncing...");const [eggs,birds,sales,uses,expenses]=await Promise.all([client.from("egg_entries").select("*").order("entry_date",{ascending:false}),client.from("flock").select("*").order("created_at",{ascending:false}),client.from("sales").select("*").order("sale_date",{ascending:false}),client.from("household_use").select("*").order("use_date",{ascending:false}),client.from("expenses").select("*").order("expense_date",{ascending:false})]);let err=[eggs,birds,sales,uses,expenses].find(r=>r.error);if(err){setStatus("Sync failed: "+err.error.message);return}data={eggs:eggs.data,birds:birds.data,sales:sales.data,uses:uses.data,expenses:expenses.data};render();setStatus("Synced "+new Date().toLocaleTimeString())}
async function insert(table,row){setStatus("Saving...");let {error}=await client.from(table).insert(row);if(error){alert(error.message);setStatus("Save failed")}else await loadAll()}async function del(table,id){if(!confirm("Delete this record?"))return;let {error}=await client.from(table).delete().eq("id",id);if(error)alert(error.message);else await loadAll()}
$("eggForm").onsubmit=e=>{e.preventDefault();insert("egg_entries",{entry_date:$("eggDate").value,eggs_collected:num($("eggCollected").value),broken_discarded:num($("eggBroken").value),notes:$("eggNotes").value});e.target.reset();dates()};$("birdForm").onsubmit=e=>{e.preventDefault();insert("flock",{name:$("birdName").value,breed:$("birdBreed").value,status:$("birdStatus").value,acquired_date:$("birdDate").value||null,notes:$("birdNotes").value});e.target.reset()};$("saleForm").onsubmit=e=>{e.preventDefault();insert("sales",{sale_date:$("saleDate").value,customer:$("saleCustomer").value,dozens:num($("saleDozens").value),price_per_dozen:num($("salePrice").value),paid:$("salePaid").value==="true",notes:$("saleNotes").value});e.target.reset();$("salePrice").value="5.00";dates()};$("useForm").onsubmit=e=>{e.preventDefault();insert("household_use",{use_date:$("useDate").value,eggs_used:num($("useEggs").value),purpose:$("usePurpose").value});e.target.reset();dates()};$("expenseForm").onsubmit=e=>{e.preventDefault();insert("expenses",{expense_date:$("expenseDate").value,category:$("expenseCategory").value,amount:num($("expenseAmount").value),notes:$("expenseNotes").value});e.target.reset();dates()};
function table(id,rows,headers,map,tableName){$(id).innerHTML="<tr>"+headers.map(h=>`<th>${h}</th>`).join("")+"<th></th></tr>"+rows.map(r=>"<tr>"+map(r).map(v=>`<td>${v??""}</td>`).join("")+`<td><button onclick="del('${tableName}','${r.id}')">Delete</button></td></tr>`).join("")}
function render(){let d=today(),ym=d.slice(0,7),w=new Date();w.setDate(w.getDate()-6);let ws=w.toISOString().slice(0,10),col=data.eggs.reduce((a,x)=>a+num(x.eggs_collected),0),bad=data.eggs.reduce((a,x)=>a+num(x.broken_discarded),0),sold=data.sales.reduce((a,x)=>a+num(x.dozens)*12,0),used=data.uses.reduce((a,x)=>a+num(x.eggs_used),0),active=data.birds.filter(x=>["Laying","Molting","Broody"].includes(x.status)).length,week=data.eggs.filter(x=>x.entry_date>=ws).reduce((a,x)=>a+num(x.eggs_collected),0);$("todayEggs").textContent=data.eggs.filter(x=>x.entry_date===d).reduce((a,x)=>a+num(x.eggs_collected),0);$("weekEggs").textContent=week;$("inventoryEggs").textContent=Math.round(col-bad-sold-used);$("monthSales").textContent=money(data.sales.filter(x=>x.sale_date?.startsWith(ym)).reduce((a,x)=>a+num(x.dozens)*num(x.price_per_dozen),0));$("monthEggs").textContent=data.eggs.filter(x=>x.entry_date?.startsWith(ym)).reduce((a,x)=>a+num(x.eggs_collected),0);$("activeLayers").textContent=active;$("eggsPerHen").textContent=active?(week/active).toFixed(1):"0";$("monthExpenses").textContent=money(data.expenses.filter(x=>x.expense_date?.startsWith(ym)).reduce((a,x)=>a+num(x.amount),0));table("recentEggTable",data.eggs.slice(0,10),["Date","Collected","Broken","Notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes],"egg_entries");table("eggTable",data.eggs,["Date","Collected","Broken","Notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes],"egg_entries");table("birdTable",data.birds,["Name","Breed","Status","Date","Notes"],r=>[r.name,r.breed,r.status,r.acquired_date,r.notes],"flock");table("saleTable",data.sales,["Date","Customer","Dozens","Price","Total","Paid","Notes"],r=>[r.sale_date,r.customer,r.dozens,money(r.price_per_dozen),money(num(r.dozens)*num(r.price_per_dozen)),r.paid?"Yes":"No",r.notes],"sales");table("useTable",data.uses,["Date","Eggs","Purpose"],r=>[r.use_date,r.eggs_used,r.purpose],"household_use");table("expenseTable",data.expenses,["Date","Category","Amount","Notes"],r=>[r.expense_date,r.category,money(r.amount),r.notes],"expenses");renderReports()}

function dateOnly(dt){return new Date(dt.getFullYear(),dt.getMonth(),dt.getDate())}
function isoDate(dt){let d=dateOnly(dt);return d.toISOString().slice(0,10)}
function addDays(dt,n){let d=dateOnly(dt);d.setDate(d.getDate()+n);return d}
function addMonths(dt,n){let d=new Date(dt.getFullYear(),dt.getMonth()+n,1);return d}
function startOfWeek(dt){let d=dateOnly(dt),day=d.getDay();d.setDate(d.getDate()-day);return d}
function monthKey(dt){return dt.getFullYear()+"-"+String(dt.getMonth()+1).padStart(2,"0")}
function prettyDay(iso){let [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString(undefined,{month:"short",day:"numeric"})}
function prettyMonth(key){let [y,m]=key.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:"short",year:"2-digit"})}
function eggTotal(start,end){return data.eggs.filter(x=>x.entry_date>=start&&x.entry_date<=end).reduce((a,x)=>a+num(x.eggs_collected),0)}
function eggsByDate(){let m={};data.eggs.forEach(x=>{if(x.entry_date)m[x.entry_date]=(m[x.entry_date]||0)+num(x.eggs_collected)});return m}
function renderBarChart(rows,title,sub){let el=$("eggChart");if(!el)return;$("reportChartTitle").textContent=title;$("reportChartSub").textContent=sub;let total=rows.reduce((a,r)=>a+r.value,0);$("reportChartTotal").textContent=total+" eggs";if(!rows.length){el.innerHTML='<div class="emptyChart">No egg data yet.</div>';return}let max=Math.max(...rows.map(r=>r.value),1);el.innerHTML=rows.map(r=>`<div class="barRow"><div class="barLabel">${r.label}</div><div class="barTrack"><div class="barFill" style="width:${Math.max(3,(r.value/max)*100)}%"></div></div><div class="barValue">${r.value}</div></div>`).join("")}
function reportRows(){let map=eggsByDate(),now=dateOnly(new Date());if(reportMode==="weekly"){let start=startOfWeek(addDays(now,-77));let rows=[];for(let i=0;i<12;i++){let s=addDays(start,i*7),e=addDays(s,6),v=eggTotal(isoDate(s),isoDate(e));rows.push({label:prettyDay(isoDate(s)),value:v})}return {rows,title:"Weekly Egg Production",sub:"Last 12 calendar weeks"}}if(reportMode==="monthly"){let start=addMonths(now,-11),rows=[];for(let i=0;i<12;i++){let d=addMonths(start,i),key=monthKey(d),v=data.eggs.filter(x=>x.entry_date?.startsWith(key)).reduce((a,x)=>a+num(x.eggs_collected),0);rows.push({label:prettyMonth(key),value:v})}return {rows,title:"Monthly Egg Production",sub:"Last 12 months"}}let start=addDays(now,-29),rows=[];for(let i=0;i<30;i++){let d=isoDate(addDays(start,i));rows.push({label:prettyDay(d),value:map[d]||0})}return {rows,title:"Daily Egg Production",sub:"Last 30 days"}}
function renderReports(){if(!$('reportWtd'))return;let now=dateOnly(new Date()),wStart=startOfWeek(now),lastWStart=addDays(wStart,-7),lastWEnd=addDays(wStart,-1),mStart=new Date(now.getFullYear(),now.getMonth(),1),lastMStart=new Date(now.getFullYear(),now.getMonth()-1,1),lastMEnd=addDays(mStart,-1),all=data.eggs.filter(x=>x.entry_date).sort((a,b)=>a.entry_date.localeCompare(b.entry_date));$('reportWtd').textContent=eggTotal(isoDate(wStart),isoDate(now));$('reportLastWeek').textContent=eggTotal(isoDate(lastWStart),isoDate(lastWEnd));$('reportMtd').textContent=eggTotal(isoDate(mStart),isoDate(now));$('reportLastMonth').textContent=eggTotal(isoDate(lastMStart),isoDate(lastMEnd));let lifetime=data.eggs.reduce((a,x)=>a+num(x.eggs_collected),0);$('reportLifetime').textContent=lifetime;let uniqueDays=new Set(data.eggs.filter(x=>x.entry_date).map(x=>x.entry_date)).size;$('reportAvgDay').textContent=uniqueDays?(lifetime/uniqueDays).toFixed(1):"0";let weekTotals={},monthTotals={};data.eggs.forEach(x=>{if(!x.entry_date)return;let d=new Date(x.entry_date+"T00:00:00"),wk=isoDate(startOfWeek(d)),mk=x.entry_date.slice(0,7);weekTotals[wk]=(weekTotals[wk]||0)+num(x.eggs_collected);monthTotals[mk]=(monthTotals[mk]||0)+num(x.eggs_collected)});$('reportBestWeek').textContent=Math.max(0,...Object.values(weekTotals));$('reportBestMonth').textContent=Math.max(0,...Object.values(monthTotals));let r=reportRows();renderBarChart(r.rows,r.title,r.sub)}

function esc(v){return `"${String(v??"").replaceAll('"','""')}"`}function csv(rows,headers,map){return headers.join(",")+"\n"+rows.map(r=>map(r).map(esc).join(",")).join("\n")}function dl(name,content,type="text/csv"){let a=document.createElement("a"),blob=new Blob([content],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("exportEggs").onclick=()=>dl("shearin-farm-eggs.csv",csv(data.eggs,["date","eggs_collected","broken_discarded","notes"],r=>[r.entry_date,r.eggs_collected,r.broken_discarded,r.notes]));$("exportFlock").onclick=()=>dl("shearin-farm-flock.csv",csv(data.birds,["name","breed","status","date","notes"],r=>[r.name,r.breed,r.status,r.acquired_date,r.notes]));$("exportSales").onclick=()=>dl("shearin-farm-sales.csv",csv(data.sales,["date","customer","dozens","price_per_dozen","paid","notes"],r=>[r.sale_date,r.customer,r.dozens,r.price_per_dozen,r.paid,r.notes]));$("exportUse").onclick=()=>dl("shearin-farm-use.csv",csv(data.uses,["date","eggs_used","purpose"],r=>[r.use_date,r.eggs_used,r.purpose]));$("exportExpenses").onclick=()=>dl("shearin-farm-expenses.csv",csv(data.expenses,["date","category","amount","notes"],r=>[r.expense_date,r.category,r.amount,r.notes]));$("exportBackup").onclick=()=>dl("shearin-farm-backup.json",JSON.stringify(data,null,2),"application/json");
function parseCSV(text){let lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];let headers=lines[0].split(",").map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{let parts=line.split(",");let obj={};headers.forEach((h,i)=>obj[h]=(parts[i]||"").trim());return obj})}
$("previewEggImport").onclick=()=>{pendingImport=parseCSV($("eggImportText").value).map(r=>({entry_date:r.date,eggs_collected:num(r.eggs_collected),broken_discarded:num(r.broken_discarded),notes:r.notes||""})).filter(r=>r.entry_date);$("importMessage").textContent=`Previewing ${pendingImport.length} rows.`;$("runEggImport").classList.toggle("hidden",pendingImport.length===0);$("importPreviewTable").innerHTML="<tr><th>Date</th><th>Eggs</th><th>Broken</th><th>Notes</th></tr>"+pendingImport.map(r=>`<tr><td>${r.entry_date}</td><td>${r.eggs_collected}</td><td>${r.broken_discarded}</td><td>${r.notes}</td></tr>`).join("")};
$("runEggImport").onclick=async()=>{if(!pendingImport.length)return;if(!confirm(`Import ${pendingImport.length} egg rows?`))return;let {error}=await client.from("egg_entries").insert(pendingImport);if(error){$("importMessage").textContent=error.message}else{$("importMessage").textContent="Import complete.";pendingImport=[];$("runEggImport").classList.add("hidden");await loadAll()}};
if("serviceWorker"in navigator){navigator.serviceWorker.register("sw.js?v=7").catch(()=>{})}init();